/** Generated by @lead/vector [codex] · 2026-08-24 */
import assert from "node:assert/strict";
import test from "node:test";

async function worker() {
  const workerUrl = new URL("../dist/server/index.js", import.meta.url);
  workerUrl.searchParams.set("test", `${process.pid}-${Date.now()}`);
  return (await import(workerUrl.href)).default;
}

test("server-renders the DOVA Hub shell", async () => {
  const app = await worker();
  const response = await app.fetch(
    new Request("http://localhost/", { headers: { accept: "text/html" } }),
    { ASSETS: { fetch: async () => new Response("Not found", { status: 404 }) } },
    { waitUntil() {}, passThroughOnException() {} },
  );
  assert.equal(response.status, 200);
  const html = await response.text();
  assert.match(html, /<title>DOVA Hub<\/title>/i);
  assert.match(html, /Your work, one clear view\./i);
  assert.match(html, /DOVA Intelligence/i);
  assert.match(html, /OneDrive/i);
  assert.doesNotMatch(html, /sk-proj-|OPENAI_API_KEY/);
});

test("reports integration state without returning secrets", async () => {
  const app = await worker();
  const response = await app.fetch(
    new Request("http://localhost/api/status"),
    { ASSETS: { fetch: async () => new Response("Not found", { status: 404 }) } },
    { waitUntil() {}, passThroughOnException() {} },
  );
  assert.equal(response.status, 200);
  const payload = await response.json();
  assert.equal(typeof payload.openai.configured, "boolean");
  assert.equal(payload.openai.model, "gpt-5.4-mini");
  assert.equal("key" in payload.openai, false);
});
