/** Generated by @lead/vector [codex] · 2026-08-24 */
const SYSTEM_CONTEXT = `You are DOVA Intelligence inside the private DOVA Futures product Hub.
Be concise, operational, and clear. You may reason from this verified context only:
- The company website is in Dblackone/Dova-futures-website and dovafutures.com points to it.
- The pre-order product is in Dblackone/Dova-preorder.
- This repository is the product and operations Hub.
- Confidential project documents, drawings, models, invoices, and generated documents belong in OneDrive, not GitHub.
- OneDrive and the local workstation bridge are not connected yet. Never claim you searched or opened those files.
- The Hub can discuss its architecture, products, workspaces, storage policy, and implementation status.
If a request requires unavailable private files, say that the OneDrive integration must be connected first.`;

export async function POST(request: Request) {
  const apiKey = process.env.OPENAI_API_KEY;
  if (!apiKey) return Response.json({ error: "OpenAI is not configured on this Hub." }, { status: 503 });

  let prompt = "";
  try {
    const body = await request.json() as { prompt?: unknown };
    prompt = typeof body.prompt === "string" ? body.prompt.trim() : "";
  } catch {
    return Response.json({ error: "The request body must be valid JSON." }, { status: 400 });
  }
  if (!prompt) return Response.json({ error: "Enter a question for DOVA Intelligence." }, { status: 400 });
  if (prompt.length > 6000) return Response.json({ error: "Keep the request under 6,000 characters." }, { status: 413 });

  const response = await fetch("https://api.openai.com/v1/responses", {
    method: "POST",
    headers: { authorization: `Bearer ${apiKey}`, "content-type": "application/json" },
    body: JSON.stringify({ model: process.env.OPENAI_MODEL || "gpt-5.4-mini", instructions: SYSTEM_CONTEXT, input: prompt, max_output_tokens: 1200, store: false }),
  });

  const data = await response.json() as { output_text?: string; output?: Array<{ content?: Array<{ type?: string; text?: string }> }>; error?: { message?: string } };
  if (!response.ok) {
    console.error("OpenAI request failed", response.status, data.error?.message || "Unknown error");
    return Response.json({ error: "DOVA Intelligence is temporarily unavailable." }, { status: 502 });
  }
  const answer = data.output_text || data.output?.flatMap((item) => item.content || []).filter((item) => item.type === "output_text").map((item) => item.text || "").join("\n").trim();
  if (!answer) return Response.json({ error: "DOVA Intelligence returned an empty response." }, { status: 502 });
  return Response.json({ answer }, { headers: { "cache-control": "no-store" } });
}
