"""Build the portable, read-only data snapshot used by the hub dashboard."""

from __future__ import annotations

import argparse
import json
import re
from datetime import datetime
from pathlib import Path


ROOT = Path(__file__).resolve().parents[3]


def field(text: str, label: str, fallback: str) -> str:
    match = re.search(rf"\*\*{re.escape(label)}:\*\*\s*(.+)", text)
    return match.group(1).strip() if match else fallback


def first_action(text: str) -> str:
    match = re.search(r"^\s*\d+\.\s+(.+)$", text, re.MULTILINE)
    return match.group(1).strip() if match else "No next action recorded"


def registry_rows(text: str) -> dict[str, dict[str, str]]:
    rows: dict[str, dict[str, str]] = {}
    for line in text.splitlines():
        match = re.match(r"\|\s*\[`([^`]+)`\]\(([^)]+)\)\s*\|\s*(.*?)\s*\|\s*(.*?)\s*\|\s*(.*?)\s*\|\s*(.*?)\s*\|", line)
        if match:
            slug, project_link, purpose, code_path, deployed, status = match.groups()
            rows[slug] = {
                "purpose": purpose.strip(),
                "codePath": code_path.strip(),
                "deployed": deployed.strip(),
                "status": status.strip(),
                "projectPath": project_link.replace("../", "", 1),
            }
    return rows


def workspace_record(workspace: Path, registry: dict[str, dict[str, str]]) -> dict[str, object]:
    slug = workspace.name
    project_path = workspace / "PROJECT.md"
    status_path = workspace / "memory" / "status.md"
    next_path = workspace / "memory" / "next-up.md"
    project_text = project_path.read_text(encoding="utf-8") if project_path.exists() else ""
    status_text = status_path.read_text(encoding="utf-8") if status_path.exists() else ""
    next_text = next_path.read_text(encoding="utf-8") if next_path.exists() else ""
    registered = registry.get(slug)
    purpose = field(project_text, "One-line purpose", "Workspace context")
    if registered:
        code_path = registered["codePath"]
        status = registered["status"] or field(status_text, "Status", "Status unavailable")
    else:
        code_path = f"workspaces/{slug}/"
        status = field(status_text, "Status", "Not registered in company/registry.md")
    return {
        "slug": slug,
        "purpose": purpose,
        "status": status,
        "codePath": code_path,
        "nextAction": first_action(next_text),
        "registered": bool(registered),
        "projectPath": f"workspaces/{slug}/PROJECT.md",
        "statusPath": f"workspaces/{slug}/memory/status.md",
    }


def build(root: Path) -> dict[str, object]:
    registry_file = root / "company" / "registry.md"
    registry = registry_rows(registry_file.read_text(encoding="utf-8")) if registry_file.exists() else {}
    workspaces_root = root / "workspaces"
    workspaces = [
        workspace_record(path, registry)
        for path in sorted(workspaces_root.iterdir())
        if path.is_dir() and path.name != "_TEMPLATE" and (path / "PROJECT.md").exists()
    ]
    return {
        "generatedAt": datetime.now().astimezone().strftime("%Y-%m-%d %H:%M %Z"),
        "workspaces": workspaces,
    }


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--root", type=Path, default=ROOT, help="Repository root")
    parser.add_argument("--output", type=Path, default=Path(__file__).with_name("snapshot.js"), help="Snapshot JavaScript path")
    args = parser.parse_args()
    payload = json.dumps(build(args.root.resolve()), ensure_ascii=False, indent=2)
    args.output.write_text(f"// Generated by build_snapshot.py. Do not edit by hand.\nwindow.DOVA_HUB_SNAPSHOT = {payload};\n", encoding="utf-8")
    print(f"Wrote {args.output}")


if __name__ == "__main__":
    main()
