// Generated by build_snapshot.py. Do not edit by hand.
window.DOVA_HUB_SNAPSHOT = {
  "generatedAt": "2026-08-19 18:12 W. Central Africa Standard Time",
  "workspaces": [
    {
      "slug": "bim-standards",
      "purpose": "The firm-wide Revit naming system (projects, sheets,",
      "status": "Tools verified live in Revit (2 bugs fixed); Architecture .rte built; QA on real firm project pending",
      "codePath": "`bim-standards/`",
      "nextAction": "[ ] **Independent checker review of BIM-04 naming updates** — verify the",
      "registered": true,
      "projectPath": "workspaces/bim-standards/PROJECT.md",
      "statusPath": "workspaces/bim-standards/memory/status.md"
    },
    {
      "slug": "client-jobs",
      "purpose": "Container for every paid client project — documents,",
      "status": "3 active: FHS Pool (Ibafo), C.K. Musa road (Afuze), Hall of Worship (Osogbo)",
      "codePath": "`projects/`",
      "nextAction": "[ ] **ROAD: client decision on QTE-2026-001** — quote is approved by the",
      "registered": true,
      "projectPath": "workspaces/client-jobs/PROJECT.md",
      "statusPath": "workspaces/client-jobs/memory/status.md"
    },
    {
      "slug": "company-ops",
      "purpose": "Internal and administrative work not tied to one client",
      "status": "Baseline scaffold",
      "codePath": "`automations/`, registers, admin docs",
      "nextAction": "[ ] **Confirm connector list** — with principal: tick the connectors actually",
      "registered": true,
      "projectPath": "workspaces/company-ops/PROJECT.md",
      "statusPath": "workspaces/company-ops/memory/status.md"
    },
    {
      "slug": "document-templates",
      "purpose": "The canonical library of branded company document",
      "status": "10 templates (incl. 00-Letterhead) + design system; Express wiring pending",
      "codePath": "`documents/` (+ `documents/_ds/`, `scripts/`)",
      "nextAction": "[ ] **GATE — principal reviews the Phase 2 samples.** `drafts/samples/` (ten",
      "registered": true,
      "projectPath": "workspaces/document-templates/PROJECT.md",
      "statusPath": "workspaces/document-templates/memory/status.md"
    },
    {
      "slug": "dova-futures-intelligence",
      "purpose": "Local-first desktop AI orchestration platform for DOVA Futures.",
      "status": "Active - read-only offline hub dashboard prototype implemented; website/store migration awaits destination repositories.",
      "codePath": "workspaces/dova-futures-intelligence/",
      "nextAction": "Provide the destination GitHub repositories for the website and preorder store, then prepare a verified migration plan before touching deploy-critical paths.",
      "registered": false,
      "projectPath": "workspaces/dova-futures-intelligence/PROJECT.md",
      "statusPath": "workspaces/dova-futures-intelligence/memory/status.md"
    },
    {
      "slug": "preorder-store",
      "purpose": "Preorder/e-commerce sale platform for DOVA Futures —",
      "status": "Built; needs live env vars + persistence decision",
      "codePath": "`dova-preorder/`",
      "nextAction": "[ ] **Security/QA check of the payment flow** — dispatch @sec/warden +",
      "registered": true,
      "projectPath": "workspaces/preorder-store/PROJECT.md",
      "statusPath": "workspaces/preorder-store/memory/status.md"
    },
    {
      "slug": "website",
      "purpose": "Lead-generation + brand-credibility site for DOVA",
      "status": "Live; backend SMTP + social links still pending",
      "codePath": "repo **root**: `index.html`, `server.js`, `data/`, `public/`, `assets/`",
      "nextAction": "[ ] **Export and review the website handover** — move",
      "registered": true,
      "projectPath": "workspaces/website/PROJECT.md",
      "statusPath": "workspaces/website/memory/status.md"
    }
  ]
};
