"use client";

/** Generated by @lead/vector [codex] · 2026-08-24 */

import { FormEvent, useEffect, useMemo, useState } from "react";

type Page = "Overview" | "DOVA Intelligence" | "Projects" | "Files" | "Workspaces" | "Products" | "Attention" | "Activity" | "Repository Guide" | "Settings";
type IntegrationStatus = { openai: { configured: boolean; model: string }; oneDrive: { configured: boolean }; workstation: { configured: boolean } };
type Message = { role: "assistant" | "user"; text: string };

const primaryNav: Page[] = ["Overview", "DOVA Intelligence", "Projects", "Files", "Workspaces", "Products"];
const operationsNav: Page[] = ["Attention", "Activity", "Repository Guide", "Settings"];
const icons: Record<Page, string> = {
  Overview: "◫", "DOVA Intelligence": "✦", Projects: "◇", Files: "▤", Workspaces: "▦",
  Products: "⬡", Attention: "!", Activity: "↻", "Repository Guide": "≡", Settings: "⚙",
};

const products = [
  { mark: "W", name: "DOVA Website", domain: "dovafutures.com", detail: "Public company website in its dedicated repository.", status: "Live", tone: "healthy" },
  { mark: "H", name: "DOVA Hub", domain: "hub.dovafutures.com", detail: "Private product, workspace and intelligence dashboard.", status: "Deployed", tone: "healthy" },
  { mark: "P", name: "DOVA Pre-order", domain: "preorder.dovafutures.com", detail: "Pre-order application in its dedicated repository.", status: "Repository linked", tone: "pending" },
] as const;

const workspaces = [
  { name: "DOVA Futures Intelligence", scope: "Hub, orchestration and intelligence", status: "Active", next: "Connect approved live services" },
  { name: "Company Operations", scope: "Governance, templates and company records", status: "Active", next: "Complete OneDrive inventory" },
  { name: "Website", scope: "Reference and migration tracking", status: "Separated", next: "Validate production ownership" },
  { name: "Pre-order Store", scope: "Reference and product tracking", status: "Separated", next: "Configure deployment domain" },
] as const;

const attention = [
  { icon: "DNS", title: "Add Hub DNS records", note: "Namecheap CNAME: hub → custom-domains.chatgpt.site, plus the two verification TXT records", status: "Owner action", tone: "attention" },
  { icon: "1D", title: "Connect Microsoft OneDrive", note: "Requires an approved Microsoft Entra app and folder scope", status: "Not connected", tone: "pending" },
] as const;

function initials(name: string) {
  return name.split(/\s+/).filter(Boolean).slice(0, 2).map((part) => part[0]).join("").toUpperCase();
}

export function HubDashboard({ userName, userEmail }: { userName: string; userEmail: string | null }) {
  const [page, setPage] = useState<Page>("Overview");
  const [menuOpen, setMenuOpen] = useState(false);
  const [status, setStatus] = useState<IntegrationStatus | null>(null);

  useEffect(() => {
    fetch("/api/status").then((response) => response.ok ? response.json() : null).then(setStatus).catch(() => setStatus(null));
  }, []);

  function navigate(next: Page) {
    setPage(next);
    setMenuOpen(false);
    window.scrollTo({ top: 0, behavior: "smooth" });
  }

  return (
    <div className="hub-shell">
      <button className={`sidebar-scrim ${menuOpen ? "open" : ""}`} aria-label="Close navigation" onClick={() => setMenuOpen(false)} />
      <aside className={`sidebar ${menuOpen ? "open" : ""}`}>
        <div className="brand"><span className="brand-mark">D</span><div><strong>DOVA HUB</strong><small>PRODUCT INTELLIGENCE</small></div></div>
        <div className="nav-label">WORKSPACE</div>
        {primaryNav.map((item) => <NavButton key={item} item={item} active={page === item} onClick={() => navigate(item)} />)}
        <div className="nav-label">OPERATIONS</div>
        {operationsNav.map((item) => <NavButton key={item} item={item} active={page === item} count={item === "Attention" ? attention.length : undefined} onClick={() => navigate(item)} />)}
        <div className="side-status">
          <strong>{status?.openai.configured ? "DOVA Intelligence ready" : "Checking integrations…"}</strong>
          <span>OneDrive {status?.oneDrive.configured ? "connected" : "not connected"} · private access boundary</span>
        </div>
      </aside>

      <div className="app-column">
        <header className="topbar">
          <button className="mobile-menu" aria-label="Open navigation" onClick={() => setMenuOpen(true)}>☰</button>
          <span className="top-title">{page}</span>
          <button className="search-button" onClick={() => navigate("DOVA Intelligence")}><span>⌕</span> Search the Hub or ask DOVA <kbd>AI</kbd></button>
          <button className="avatar" title={userEmail ?? userName} aria-label={`Account: ${userName}`}>{initials(userName)}</button>
        </header>
        <main className="content">
          <PageContent page={page} navigate={navigate} status={status} />
        </main>
      </div>

      <nav className="mobile-bottom" aria-label="Mobile navigation">
        {(["Overview", "DOVA Intelligence", "Projects", "Files", "Settings"] as Page[]).map((item) => (
          <button key={item} className={page === item ? "active" : ""} onClick={() => navigate(item)}><span>{icons[item]}</span>{item === "DOVA Intelligence" ? "Intel" : item}</button>
        ))}
      </nav>
    </div>
  );
}

function NavButton({ item, active, count, onClick }: { item: Page; active: boolean; count?: number; onClick: () => void }) {
  return <button className={`nav-button ${active ? "active" : ""}`} onClick={onClick}><span className="nav-icon">{icons[item]}</span>{item}{count ? <span className="count">{count}</span> : null}</button>;
}

function PageContent({ page, navigate, status }: { page: Page; navigate: (page: Page) => void; status: IntegrationStatus | null }) {
  if (page === "Overview") return <Overview navigate={navigate} status={status} />;
  if (page === "DOVA Intelligence") return <Intelligence status={status} />;
  if (page === "Projects") return <CloudLibrary kind="projects" />;
  if (page === "Files") return <CloudLibrary kind="files" />;
  if (page === "Workspaces") return <Workspaces />;
  if (page === "Products") return <Products />;
  if (page === "Attention") return <Attention />;
  if (page === "Activity") return <Activity />;
  if (page === "Repository Guide") return <Guide />;
  return <Settings status={status} />;
}

function Heading({ title, description, children }: { title: string; description: string; children?: React.ReactNode }) {
  return <div className="page-heading"><div><span className="eyebrow">DOVA PRODUCT HUB</span><h1>{title}</h1><p>{description}</p></div>{children ? <div className="heading-actions">{children}</div> : null}</div>;
}

function Overview({ navigate, status }: { navigate: (page: Page) => void; status: IntegrationStatus | null }) {
  return <>
    <Heading title="Overview" description="A clear view of DOVA’s products, workspaces, decisions and connected services." />
    <section className="hero-strip">
      <div className="hero-copy"><span className="eyebrow">OPERATING VIEW · PRIVATE</span><h2>Your work, one clear view.</h2><p>The Hub keeps application code and operational context easy to find while confidential project documents remain in OneDrive.</p></div>
      <div className="hero-aside"><span>DOVA INTELLIGENCE</span><strong>{status?.openai.configured ? "The cloud reasoning service is ready." : "Checking the cloud reasoning service."}</strong><button className="hero-link" onClick={() => navigate("DOVA Intelligence")}>Open Intelligence →</button></div>
    </section>
    <div className="metric-grid">
      <Metric label="PRODUCTS" value={products.length} note="Separate repositories, one Hub" />
      <Metric label="WORKSPACES" value={workspaces.length} note="Visible operational areas" />
      <Metric label="ATTENTION" value={attention.length} note="Configuration actions remaining" />
      <Metric label="ONEDRIVE" value={status?.oneDrive.configured ? "READY" : "WAIT"} note={status?.oneDrive.configured ? "Connection configured" : "No client files exposed"} />
    </div>
    <div className="section-grid">
      <section className="panel"><div className="panel-head"><strong>Needs attention</strong><button className="text-action" onClick={() => navigate("Attention")}>Open queue</button></div>{attention.map((item) => <ListRow key={item.title} {...item} />)}</section>
      <section className="panel"><div className="panel-head"><strong>Quick access</strong><span className="card-note">Common destinations</span></div><div className="quick-grid">
        <Quick icon="✦" title="Ask DOVA" note="Use cloud intelligence" onClick={() => navigate("DOVA Intelligence")} />
        <Quick icon="◇" title="Projects" note="OneDrive-backed records" onClick={() => navigate("Projects")} />
        <Quick icon="▦" title="Workspaces" note="Find repo context" onClick={() => navigate("Workspaces")} />
        <Quick icon="⬡" title="Products" note="Review digital surfaces" onClick={() => navigate("Products")} />
      </div></section>
    </div>
  </>;
}

function Metric({ label, value, note }: { label: string; value: string | number; note: string }) {
  return <article className="card metric-card"><span className="card-label">{label}</span><strong className="metric-value">{value}</strong><span className="card-note">{note}</span></article>;
}

function Quick({ icon, title, note, onClick }: { icon: string; title: string; note: string; onClick: () => void }) {
  return <button className="quick-card" onClick={onClick}><span>{icon}</span><strong>{title}</strong><small>{note}</small></button>;
}

function ListRow({ icon, title, note, status, tone }: { icon: string; title: string; note: string; status: string; tone: string }) {
  return <div className="list-row"><span className="row-icon">{icon}</span><div className="row-copy"><strong>{title}</strong><small>{note}</small></div><span className={`badge ${tone}`}>{status}</span></div>;
}

function Products() {
  return <><Heading title="Products" description="The public and private digital surfaces that make up the DOVA product family." /><div className="cards-3">{products.map((product) => <article className="card feature-card" key={product.name}><span className="row-icon">{product.mark}</span><h3>{product.name}</h3><p>{product.detail}</p><p className="domain">{product.domain}</p><span className={`badge ${product.tone}`}>{product.status}</span></article>)}</div></>;
}

function Workspaces() {
  return <><Heading title="Workspaces" description="The repository organised by responsibility, context and safe write scope." /><section className="panel table"><div className="table-row head"><span>WORKSPACE</span><span>SCOPE</span><span>STATUS</span><span>NEXT</span></div>{workspaces.map((item) => <div className="table-row" key={item.name}><strong>{item.name}</strong><span>{item.scope}</span><span>{item.status}</span><span>{item.next}</span></div>)}</section></>;
}

function CloudLibrary({ kind }: { kind: "projects" | "files" }) {
  const isProjects = kind === "projects";
  return <><Heading title={isProjects ? "Projects" : "Files"} description={isProjects ? "Construction and client work will appear here from approved OneDrive project folders." : "Search and open authorised project records without copying confidential documents into GitHub."}><button className="button secondary" disabled>Connect OneDrive</button></Heading>
    <section className="panel empty-state"><div className="empty-state-inner"><div className="empty-symbol">☁</div><h3>OneDrive is not connected yet</h3><p>No project names, documents or client files are being simulated. Once Microsoft access is configured, this area can read approved metadata and open source files in OneDrive.</p><button className="button primary" disabled>Microsoft connection required</button><div className="policy-box">Storage boundary: project drawings, models, photographs, correspondence and generated documents stay in OneDrive. GitHub contains code, safe metadata and references only.</div></div></section>
  </>;
}

function Attention() {
  return <><Heading title="Attention" description="Configuration choices and approvals that require the owner’s review." /><section className="panel">{attention.map((item) => <ListRow key={item.title} {...item} />)}</section></>;
}

function Activity() {
  const items = [
    { icon: "AI", title: "Dedicated OpenAI key configured", note: "Stored locally as a secret; not committed", status: "Current", tone: "healthy" },
    { icon: "WEB", title: "Website domain transferred", note: "dovafutures.com now resolves to the website repository", status: "Verified", tone: "healthy" },
    { icon: "HUB", title: "Private Hub application deployed", note: "Responsive dashboard and server-side DOVA Intelligence", status: "Verified", tone: "healthy" },
  ];
  return <><Heading title="Activity" description="A concise record of material Hub and product changes." /><section className="panel">{items.map((item) => <ListRow key={item.title} {...item} />)}</section></>;
}

function Guide() {
  return <><Heading title="Repository guide" description="Understand what lives here, what moved out, and where to begin." /><div className="guide-layout"><aside className="panel guide-nav"><div className="active">Start here</div><div>Repository map</div><div>Workspaces</div><div>Products</div><div>Storage boundary</div><div>Agent governance</div></aside><article className="panel guide-article"><span className="eyebrow">START HERE</span><h3>The DOVA product hub</h3><p>This repository is the operational centre for DOVA Futures. The company website and pre-order application now live in dedicated repositories, while this Hub provides the friendly entry point.</p><h4>How to navigate</h4><ol><li>Use Products for deployed and planned digital surfaces.</li><li>Use Workspaces to find repository context and current direction.</li><li>Use Projects and Files for approved OneDrive-backed records.</li><li>Use Attention for decisions and integrations requiring review.</li></ol><h4>Where files belong</h4><p>Code and safe operational metadata belong in GitHub. Confidential client and construction documents belong in OneDrive. The Hub connects the two without making OneDrive files public.</p></article></div></>;
}

function Settings({ status }: { status: IntegrationStatus | null }) {
  const rows = [
    { icon: "AI", title: "OpenAI", note: status?.openai.configured ? `Server key ready · ${status.openai.model}` : "Server key not detected", status: status?.openai.configured ? "Ready" : "Check", tone: status?.openai.configured ? "healthy" : "attention" },
    { icon: "1D", title: "Microsoft OneDrive", note: "Private project library and generated outputs", status: status?.oneDrive.configured ? "Ready" : "Not connected", tone: status?.oneDrive.configured ? "healthy" : "pending" },
    { icon: "PC", title: "Workstation bridge", note: "Optional local model and filesystem access", status: status?.workstation.configured ? "Ready" : "Planned", tone: "pending" },
    { icon: "GH", title: "GitHub", note: "Code, configuration and safe references", status: "Repository", tone: "private" },
  ];
  return <><Heading title="Settings & integrations" description="Connection status, storage boundaries and future local capabilities." /><section className="panel"><div className="panel-head"><strong>Connected services</strong><span className="card-note">Secrets stay server-side</span></div>{rows.map((item) => <ListRow key={item.title} {...item} />)}</section><div className="policy-box">The Hub does not display API keys, copy confidential OneDrive files into GitHub, or claim a connection before the corresponding credentials are configured.</div></>;
}

function Intelligence({ status }: { status: IntegrationStatus | null }) {
  const [messages, setMessages] = useState<Message[]>([{ role: "assistant", text: "I’m DOVA Intelligence. I can help interpret the Hub’s current product and workspace context. OneDrive content is not available until that integration is connected." }]);
  const [prompt, setPrompt] = useState("");
  const [sending, setSending] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const suggested = useMemo(() => ["Summarise the current Hub setup.", "What configuration work remains?", "Explain the storage boundary in plain language."], []);

  async function send(event: FormEvent) {
    event.preventDefault();
    const text = prompt.trim();
    if (!text || sending) return;
    setPrompt(""); setError(null); setMessages((current) => [...current, { role: "user", text }]); setSending(true);
    try {
      const response = await fetch("/api/intelligence", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ prompt: text }) });
      const data = await response.json() as { answer?: string; error?: string };
      if (!response.ok || !data.answer) throw new Error(data.error || "DOVA Intelligence could not respond.");
      setMessages((current) => [...current, { role: "assistant", text: data.answer! }]);
    } catch (cause) { setError(cause instanceof Error ? cause.message : "DOVA Intelligence could not respond."); }
    finally { setSending(false); }
  }

  return <><Heading title="DOVA Intelligence" description="A secure cloud reasoning layer for Hub context now, with OneDrive and workstation context added only after approval." />
    <div className="intel-layout"><section className="panel chat-panel"><div className="panel-head"><strong>Conversation</strong><span className={`badge ${status?.openai.configured ? "healthy" : "attention"}`}>{status?.openai.configured ? "Cloud ready" : "Checking"}</span></div><div className="chat-log" aria-live="polite">{messages.map((message, index) => <div key={`${message.role}-${index}`} className={`message ${message.role}`}>{message.text}</div>)}{sending ? <div className="message">Thinking…</div> : null}{error ? <p className="card-note error-note">{error}</p> : null}</div><form className="composer" onSubmit={send}><textarea value={prompt} maxLength={6000} onChange={(event) => setPrompt(event.target.value)} placeholder="Ask about products, workspaces, repository structure or next actions…" aria-label="Message DOVA Intelligence" /><div className="composer-row"><span>Hub context only · no OneDrive files connected</span><button className="button primary" disabled={sending || !prompt.trim()}>{sending ? "Working…" : "Send ↑"}</button></div></form></section>
      <aside className="context-stack"><article className="card context-card"><span className="card-label">CURRENT CONTEXT</span><h3>Repository Hub</h3><p>Products, workspaces, integration status and the approved storage policy.</p></article><article className="card context-card"><span className="card-label">SUGGESTED</span>{suggested.map((item) => <button key={item} className="prompt-chip" onClick={() => setPrompt(item)}>{item}</button>)}</article><article className="card context-card"><span className="card-label">BOUNDARY</span><h3>OneDrive disconnected</h3><p>DOVA Intelligence cannot see project files or client records at this stage.</p></article></aside>
    </div></>;
}
