const swatches = [
  ['FOREST 700','#1C4636','light'],['GREEN 900','#102A20','light'],['TERRACOTTA','#B85C38','light'],['WARM CREAM','#F5EFE8','dark'],
  ['SAND','#E8E1D5','dark'],['INK 900','#1A1A1A','light'],['MINT FOCUS','#5AA17C','light'],['WHITE','#FFFFFF','dark']
];
document.querySelector('#swatches').innerHTML = swatches.map(([name,hex,tone]) => `<div class="swatch" style="background:${hex};color:${tone==='light'?'#fff':'#1a1a1a'}"><span>${name}</span><small>${hex}</small></div>`).join('');

const screens = [
  ['D-00','Secure access','auth'],['D-01','Overview','overview'],['D-02','DOVA Intelligence','intelligence'],['D-03','Projects','projects'],
  ['D-04','Project detail','project'],['D-05','Files browser','files'],['D-06','File insight','fileInsight'],['D-07','Workspaces','workspaces'],
  ['D-08','Workspace detail','workspace'],['D-09','Products','products'],['D-10','Attention queue','attention'],['D-11','Approval detail','approval'],
  ['D-12','Activity','activity'],['D-13','Repository guide','guide'],['D-14','Settings & integrations','settings'],['D-15','Workstation connection','connection'],
  ['D-16','OneDrive project library','oneDrive'],['D-17','Create project document','output']
];
const nav = ['Overview','DOVA Intelligence','Projects','Files','OneDrive','Workspaces','Products','Attention','Activity','Repository Guide','Settings'];
const icon = name => ({Overview:'◫','DOVA Intelligence':'✦',Projects:'◇',Files:'▤',OneDrive:'☁',Workspaces:'▦',Products:'⬡',Attention:'!',Activity:'↻','Repository Guide':'≡',Settings:'⚙'})[name] || '•';
const rows = (items) => items.map((x,i)=>`<div class="list-row"><span class="row-icon">${x[0]}</span><div class="row-copy"><strong>${x[1]}</strong><small>${x[2]}</small></div><span class="tag ${i===0?'warning':i===1?'success':'neutral'}">${x[3]}</span></div>`).join('');
const heading = (title,sub,action='New item') => `<div class="page-heading"><div><span class="eyebrow">DOVA PRODUCT HUB</span><h3>${title}</h3><p>${sub}</p></div><div class="page-actions"><button class="button secondary">Export</button><button class="button primary">${action}</button></div></div>`;
const metrics = () => `<div class="grid-4"><article class="card"><div class="card-title">ACTIVE PRODUCTS</div><div class="card-value">03</div><div class="card-sub">Website · Hub · Pre-order</div></article><article class="card"><div class="card-title">WORKSPACES</div><div class="card-value">07</div><div class="card-sub">6 healthy · 1 attention</div></article><article class="card"><div class="card-title">OPEN DECISIONS</div><div class="card-value">04</div><div class="card-sub">2 require approval</div></article><article class="card"><div class="card-title">LOCAL BRIDGE</div><div class="card-value">ON</div><div class="card-sub">Workstation connected</div></article></div>`;
const table = (kind='project') => `<div class="table"><div class="table-row head"><span>${kind==='project'?'PROJECT':'WORKSPACE'}</span><span>STATUS</span><span>OWNER</span><span>UPDATED</span><span></span></div>${['DOVA Hub','DOVA Futures Website','DOVA Pre-order','DOVA Intelligence','BIM Standards'].map((n,i)=>`<div class="table-row"><strong>${n}</strong><span><i class="dot"></i> ${i===1?'Attention':'Healthy'}</span><span>${i<3?'Product':'Operations'}</span><span>${i+1}h ago</span><span>Open →</span></div>`).join('')}</div>`;

function body(type){
  if(type==='overview') return `${heading('Good morning, Vollmann','One place to review product health, decisions and current work.','Ask DOVA')}${metrics()}<div class="grid-2" style="margin-top:16px"><section class="panel"><div class="panel-head"><strong>Needs your attention</strong><span>View all</span></div>${rows([['!','Website migration validation','Deployment paths and redirects need confirmation','Review'],['✓','Pre-order repository moved','Destination repository received','Healthy'],['↻','BIM standards QA','Real-project verification is still pending','Waiting']])}</section><section class="panel"><div class="panel-head"><strong>System pulse</strong><span>Live</span></div>${rows([['●','Hub snapshot refreshed','7 workspace records indexed','Now'],['↗','Repository activity','12 changes across 3 products','Healthy'],['⌁','Workstation bridge','Local files available securely','Online']])}</section></div>`;
  if(type==='intelligence') return `${heading('DOVA Intelligence','Ask across projects, files, decisions and connected systems.','New conversation')}<div class="ai-layout"><section class="chat"><div class="message assistant">Good morning. I can review the Hub snapshot and your connected workstation context. What should we examine?</div><div class="message user">Summarise anything blocking the Hub migration.</div><div class="message assistant"><strong>Two items need attention.</strong><br><br>1. Confirm the website destination deployment before replacing the root index.<br>2. Validate repository links and paths used by the Repository Guide.<br><br>I can open either item or prepare an approval brief.</div><div class="composer">Ask a question, reference a file, or type / for actions <button class="button primary" style="float:right;height:32px">Send ↑</button></div></section><aside class="panel"><div class="panel-head"><strong>Current context</strong></div>${rows([['H','DOVA Hub','Workspace snapshot','Active'],['F','Repository Guide','2 linked files','Open'],['W','Workstation','Local bridge','Online']])}</aside></div>`;
  if(type==='projects') return `${heading('Construction projects','Secure access to live project records stored in OneDrive.','Add project reference')}<div class="grid-4"><article class="card"><div class="card-title">ACTIVE JOBS</div><div class="card-value">04</div><div class="card-sub">FHS · C.K. Musa · ICM · Grail</div></article><article class="card"><div class="card-title">PRIMARY STORAGE</div><div class="card-value">1D</div><div class="card-sub">OneDrive · Connected</div></article><article class="card"><div class="card-title">INDEXED FILES</div><div class="card-value">548</div><div class="card-sub">Private project records</div></article><article class="card"><div class="card-title">GITHUB COPIES</div><div class="card-value">00</div><div class="card-sub">References and code only</div></article></div><div style="height:16px"></div><div class="table"><div class="table-row head"><span>PROJECT</span><span>SOURCE</span><span>STATUS</span><span>UPDATED</span><span></span></div>${[['FHS Hotel — Swimming Pool, Ibafo','31 files','Active','5 Jul'],['Engineer C. K. Musa — Afuze','15 files','Awaiting decision','21 Aug'],['Ikeja City Mall — ICM','502 files','Active library','27 May'],['Grail Movement — Hall of Worship','Reports linked','Review','11 Aug']].map((x,i)=>`<div class="table-row"><strong>${x[0]}</strong><span><i class="dot" style="background:#2f6b7d"></i> OneDrive · ${x[1]}</span><span>${x[2]}</span><span>${x[3]}</span><span>Open →</span></div>`).join('')}</div>`;
  if(type==='project') return `${heading('FHS Hotel — Swimming Pool','DFL-2026-POOL-001 · Ibafo, Ogun State','Create document')}<div style="display:flex;gap:8px;margin:-10px 0 18px"><span class="tag success">OneDrive connected</span><span class="tag neutral">Client confidential</span><span class="tag neutral">31 files indexed</span></div><div class="tabs"><span class="tab active">Overview</span><span class="tab">Documents</span><span class="tab">Drawings</span><span class="tab">Models</span><span class="tab">Photos</span><span class="tab">Correspondence</span><span class="tab">Reports</span></div><div class="grid-4"><article class="card"><div class="card-title">REVIT MODELS</div><div class="card-value">21</div><div class="card-sub">OneDrive source files</div></article><article class="card"><div class="card-title">SITE PHOTOS</div><div class="card-value">06</div><div class="card-sub">JPG project evidence</div></article><article class="card"><div class="card-title">REPORTS</div><div class="card-value">03</div><div class="card-sub">PDF progress records</div></article><article class="card"><div class="card-title">OPEN INVOICES</div><div class="card-value">05</div><div class="card-sub">Confirm payment status</div></article></div><div class="grid-2" style="margin-top:16px"><section class="panel"><div class="panel-head"><strong>Project library</strong><span>Open in OneDrive</span></div>${rows([['01','Documents','Invoices, quotations and contracts','Open'],['02','Drawings','Issued and working drawings','Open'],['03','Models','Revit and coordination models','Open'],['04','Photos','Site and progress photographs','Open'],['05','Correspondence','Client and consultant records','Open'],['06','Reports','Progress and technical reports','Open']])}</section><section class="panel"><div class="panel-head"><strong>Recent project records</strong></div>${rows([['PDF','PROGRESS-REPORT-001','June 2026 · OneDrive','Open'],['PDF','INV-2026-POOL-005','Payment invoice · OneDrive','Open'],['JPG','HNM-July-2026','Site correspondence image','Open']])}</section></div>`;
  if(type==='files'||type==='fileInsight') return `${heading(type==='files'?'Project files':'Project file intelligence','Search OneDrive project records without moving them into GitHub.','Create output')}<div style="display:flex;gap:8px;margin:-10px 0 18px"><span class="tag success">OneDrive · Primary</span><span class="tag neutral">GitHub · Code only</span></div><div class="file-layout"><aside class="file-tree"><strong style="font-size:11px">OneDrive / DOVA Futures</strong>${['PROJECTS','POOL IBAFO','01 Documents','02 Drawings','03 Models','04 Photos','05 Correspondence','06 Reports'].map((x,i)=>`<div class="tree-item ${i===1?'active':''}">${i<2?'▾':'▸'} ${x}</div>`).join('')}</aside><section class="file-list"><div class="top-search" style="width:100%;margin-bottom:16px">⌕ Search FHS Pool records in OneDrive</div>${rows([['RVT','POOL-IBAFO-MODEL.rvt','Revit model · OneDrive','Open'],['PDF','PROGRESS-REPORT-001.pdf','Project report · OneDrive','Open'],['PDF','INV-2026-POOL-005.pdf','Invoice · OneDrive','Open'],['JPG','HNM-July-2026.jpg','Correspondence · OneDrive','Open'],['DOC','Pool specification.docx','Project document · OneDrive','Open']])}<div class="preview-box">${type==='fileInsight'?'PROGRESS-REPORT-001 · secured preview':'Select a OneDrive file to preview'}</div></section><aside class="file-insight"><div class="card-title">DOVA INTELLIGENCE</div><h4 style="font:400 28px 'Bebas Neue';margin:0 0 12px">${type==='fileInsight'?'PROJECT RECORD SUMMARY':'READY TO ASSIST'}</h4><p style="font-size:11px;line-height:1.65;color:var(--slate)">${type==='fileInsight'?'This report records the June 2026 FHS Pool progress. The source remains in OneDrive; the Hub retains only its secure reference and search metadata.':'Select a project record to summarise it, locate related files or prepare a new draft in the same OneDrive project folder.'}</p><button class="button primary" style="width:100%;margin-top:18px">Ask about this record</button></aside></div>`;
  if(type==='workspaces') return `${heading('Workspaces','The company repository organised by responsibility and write scope.','Refresh registry')}${table('workspace')}`;
  if(type==='workspace') return `${heading('DOVA Futures Intelligence','Local and cloud orchestration workspace.','Open locally')}<div class="tabs"><span class="tab active">Summary</span><span class="tab">Files</span><span class="tab">Status</span><span class="tab">Decisions</span><span class="tab">Activity</span></div>${metrics()}<div class="grid-2" style="margin-top:16px"><section class="panel"><div class="panel-head"><strong>Current direction</strong></div><div style="padding:22px;font-size:11px;line-height:1.7;color:var(--slate)">Cloud-accessible Hub for remote review, paired with an optional workstation model and file bridge when the local system is available.</div></section><section class="panel"><div class="panel-head"><strong>Next actions</strong></div>${rows([['1','Review UX prototype','Desktop and mobile flows','Active'],['2','Confirm API boundary','OpenAI and cloud integrations','Waiting'],['3','Implement dashboard','After design approval','Waiting']])}</section></div>`;
  if(type==='products') return `${heading('Products','DOVA’s public and internal digital surfaces.','Add product')}<div class="grid-3">${[['W','DOVA Website','dovafutures.com','Public website'],['H','DOVA Hub','hub.dovafutures.com','Internal product hub'],['P','DOVA Pre-order','preorder.dovafutures.com','Commerce platform']].map((x,i)=>`<article class="card" style="min-height:230px"><div class="row-icon" style="width:48px;height:48px;font-size:18px">${x[0]}</div><h4 style="font:400 28px 'Bebas Neue';margin:24px 0 8px">${x[1]}</h4><p style="font-size:11px;color:var(--green-700)">${x[2]}</p><p style="font-size:11px;color:var(--muted)">${x[3]}</p><span class="tag ${i===0?'warning':'success'}">${i===0?'Migration review':'Healthy'}</span></article>`).join('')}</div>`;
  if(type==='attention') return `${heading('Attention','Decisions, approvals and exceptions requiring review.','Review next')}<div class="tabs"><span class="tab active">Open 4</span><span class="tab">Waiting 3</span><span class="tab">Resolved 18</span></div><section class="panel">${rows([['!','Website deployment validation','Confirm destination repository and DNS cutover','Review'],['!','Approve Hub design direction','Desktop and mobile UX system','Review'],['↻','BIM project QA','Requires live Revit verification','Waiting'],['⌁','Configure cloud provider','OpenAI integration boundary','Waiting']])}</section>`;
  if(type==='approval') return `${heading('Approval review','Website migration validation · AP-2026-014','Approve')}<div class="grid-2"><section class="panel"><div class="panel-head"><strong>Proposed action</strong><span class="tag warning">High impact</span></div><div style="padding:24px"><h4 style="font:400 30px 'Bebas Neue'">PROMOTE HUB TO ROOT</h4><p style="font-size:11px;line-height:1.7;color:var(--slate)">Replace the current root website index only after the separate website deployment is confirmed. Preserve redirect and rollback paths.</p><div class="card" style="margin-top:18px"><div class="card-title">AFFECTED SURFACES</div><p style="font-size:11px">dovafutures.com · repository root · GitHub Pages workflow</p></div></div></section><aside class="panel"><div class="panel-head"><strong>Decision controls</strong></div><div style="padding:24px"><div class="field"><label>REVIEW NOTE</label><div>Add an optional decision note…</div></div><button class="button primary" style="width:100%;margin-top:12px">Approve action</button><button class="button secondary" style="width:100%;margin-top:10px">Reject and return</button></div></aside></div>`;
  if(type==='activity') return `${heading('Activity','A traceable history across products and workspaces.','Export log')}<section class="panel">${rows([['↻','Hub snapshot refreshed','7 workspace records · @lead/vector','Now'],['✓','Pre-order repository linked','Dova-preorder · Vollmann Akarakiri','2h'],['D','Design scope approved','Full desktop and mobile prototype','Today'],['G','Website repository received','Dova-futures-website','Yesterday'],['!','Repository Guide link failed','404 recorded for correction','Yesterday']])}</section>`;
  if(type==='guide') return `${heading('Repository guide','Understand where work lives and how to reach it.','Open registry')}<div class="guide-grid"><aside class="guide-nav"><div class="active">Start here</div><div>Repository map</div><div>Workspaces</div><div>Products</div><div>Files and memory</div><div>Agent governance</div></aside><article class="guide-article"><span class="eyebrow">START HERE</span><h4>THE DOVA PRODUCT HUB</h4><p>This repository is the operational centre for DOVA Futures. Work is separated into workspaces so that people and agents can find context without reading unrelated code.</p><h4 style="font-size:22px">How to navigate</h4><ol><li>Use Products for deployed digital surfaces.</li><li>Use Workspaces for project context, status and decisions.</li><li>Use Files when you know the content but not its location.</li><li>Use Attention for actions requiring principal review.</li></ol></article></div>`;
  if(type==='settings') return `${heading('Settings & integrations','Connections, identity, storage and safety controls.','Save changes')}<div class="guide-grid"><aside class="guide-nav"><div class="active">General</div><div>Identity & access</div><div>OneDrive storage</div><div>GitHub</div><div>OpenAI</div><div>Workstation bridge</div><div>Notifications</div></aside><article class="guide-article"><h4>CONNECTED SERVICES</h4>${rows([['1D','OneDrive','Confidential projects and generated documents','Connected'],['G','GitHub','Code, configuration and file references only','Connected'],['AI','OpenAI','Cloud DOVA Intelligence provider','Configure'],['PC','Workstation bridge','Local files and local model','Online']])}<h4 style="font-size:22px;margin-top:28px">Storage policy</h4><p>Project drawings, models, photographs, correspondence and generated company documents remain in OneDrive. GitHub stores application code, safe metadata and secure file references only.</p></article></div>`;
  if(type==='connection') return `${heading('Workstation connection','Use local files and models when your primary system is available.','Connection help')}<div class="connection"><div class="connection-card"><div class="connection-symbol">⌁</div><span class="tag success">Secure bridge available</span><h4 style="font:400 34px 'Bebas Neue';margin:20px 0 8px">CONNECT THIS WORKSTATION</h4><p style="font-size:11px;line-height:1.7;color:var(--slate)">Pair the Hub with the local DOVA Intelligence service to search private workspace files and use the on-system model.</p><button class="button primary" style="margin-top:18px">Generate pairing code</button></div></div>`;
  if(type==='oneDrive') return `${heading('OneDrive project library','The secure source of truth for client and construction records.','Sync now')}<div class="grid-4"><article class="card"><div class="card-title">CONNECTION</div><div class="card-value">LIVE</div><div class="card-sub">Microsoft OneDrive</div></article><article class="card"><div class="card-title">PROJECT ROOT</div><div class="card-value">18</div><div class="card-sub">Project folders discovered</div></article><article class="card"><div class="card-title">INDEXED RECORDS</div><div class="card-value">548</div><div class="card-sub">Across current priority jobs</div></article><article class="card"><div class="card-title">LAST INDEX</div><div class="card-value">2M</div><div class="card-sub">Metadata only · no GitHub copy</div></article></div><div class="grid-2" style="margin-top:16px"><section class="panel"><div class="panel-head"><strong>Mapped project locations</strong><span>Manage mapping</span></div>${rows([['1D','AFUZE PROJECT','15 files · PDF, RVT, DOCX','Connected'],['1D','POOL IBAFO','31 files · RVT, JPG, PDF','Connected'],['1D','IKEJA MALL','502 files · DWG, RVT, PDF, images','Connected'],['1D','Grail Center / Osogbo','Project reports and working files','Connected']])}</section><aside class="panel"><div class="panel-head"><strong>Access boundary</strong></div><div style="padding:24px"><div class="card-title">THE HUB MAY</div><p style="font-size:11px;line-height:1.7;color:var(--slate)">Search metadata, preview authorised records, create drafts inside mapped project folders and open files in OneDrive.</p><div class="card-title" style="margin-top:22px">THE HUB MAY NOT</div><p style="font-size:11px;line-height:1.7;color:var(--slate)">Copy confidential files into GitHub, expose public links, overwrite issued documents or share anything externally without approval.</p></div></aside></div>`;
  if(type==='output') return `${heading('Create project document','Generate from an approved DOVA template and save directly to OneDrive.','Create draft')}<div class="grid-2"><section class="panel"><div class="panel-head"><strong>Document setup</strong><span class="tag success">OneDrive destination</span></div><div style="padding:24px"><div class="field"><label>PROJECT</label><div>FHS Hotel — Swimming Pool, Ibafo</div></div><div class="field"><label>DOCUMENT TYPE</label><div>Payment invoice · DOVA canonical template</div></div><div class="field"><label>DESTINATION</label><div>OneDrive / DOVA Futures limited / PROJECTS / POOL IBAFO / 01 Documents</div></div><div class="field"><label>OUTPUTS</label><div>Editable HTML + approved PDF · Draft status</div></div><button class="button primary" style="margin-top:12px">Create draft in OneDrive</button></div></section><aside class="panel"><div class="panel-head"><strong>Protection summary</strong></div><div style="padding:24px"><span class="tag warning">Principal approval required before issue</span><h4 style="font:400 28px 'Bebas Neue';margin:22px 0 8px">NO CLIENT FILES IN GITHUB</h4><p style="font-size:11px;line-height:1.7;color:var(--slate)">The Hub records a safe project ID, OneDrive item reference, document type, status and timestamps. The document itself remains in the private OneDrive project folder.</p>${rows([['✓','Canonical template','Source: documents/templates','Ready'],['1D','OneDrive destination','Private project library','Ready'],['🔒','Approval gate','No external delivery','Required']])}</div></aside></div>`;
  return '';
}
function shell(title,type,mobile=false){
  if(type==='auth') return mobile?`<div class="mobile mobile-auth"><div class="brand"><span class="brand-mark">D</span><div>DOVA HUB<small>SECURE PRODUCT INTELLIGENCE</small></div></div><h3>YOUR WORK.<br>ONE CLEAR VIEW.</h3><p>Review projects, files, decisions and DOVA Intelligence from any connected device.</p><div class="auth-box"><div class="field"><label>EMAIL ADDRESS</label><div>vollmann@dovafutures.com</div></div><button class="button primary" style="width:100%">Continue securely</button></div></div>`:`<div class="desktop auth"><section class="auth-story"><span class="eyebrow">DOVA PRODUCT HUB</span><h3>YOUR WORK.<br>ONE CLEAR VIEW.</h3><p>Review products, files, approvals and project intelligence from any connected device. Link your workstation only when local context is needed.</p></section><section class="auth-form"><div class="auth-box"><span class="eyebrow">SECURE ACCESS</span><h3>WELCOME BACK</h3><p style="font-size:11px;color:var(--muted)">Continue with your authorised DOVA account.</p><div class="field"><label>EMAIL ADDRESS</label><div>vollmann@dovafutures.com</div></div><button class="button primary" style="width:100%">Continue securely</button></div></section></div>`;
  if(mobile) return `<div class="mobile"><header class="mobile-top"><span class="brand-mark">D</span><strong>${title}</strong><button>⌕</button></header><div class="mobile-content">${body(type)}</div><nav class="bottom-nav">${['Overview','Intel','Projects','Files','More'].map((x,i)=>`<div class="${(type==='overview'&&i===0)||(type==='intelligence'&&i===1)||(type==='projects'&&i===2)||(type.includes('file')&&i===3)?'active':''}"><i>${['◫','✦','◇','▤','•••'][i]}</i>${x}</div>`).join('')}</nav></div>`;
  const active= title==='Project detail'||title==='Create project document'?'Projects':title==='File insight'?'Files':title==='OneDrive project library'?'OneDrive':title==='Workspace detail'?'Workspaces':title==='Approval detail'?'Attention':title.includes('Workstation')?'Settings':title;
  return `<div class="desktop"><aside class="sidebar"><div class="brand"><span class="brand-mark">D</span><div>DOVA HUB<small>PRODUCT INTELLIGENCE</small></div></div><div class="nav-group-label">WORKSPACE</div>${nav.slice(0,7).map(x=>`<div class="nav-item ${active===x?'active':''}"><span>${icon(x)}</span>${x}</div>`).join('')}<div class="nav-group-label">OPERATIONS</div>${nav.slice(7).map(x=>`<div class="nav-item ${active===x?'active':''}"><span>${icon(x)}</span>${x}${x==='Attention'?'<b>4</b>':''}</div>`).join('')}<div class="side-footer"><strong>OneDrive + workstation connected</strong>Private project index · 2 minutes ago</div></aside><section class="app"><header class="topbar"><span class="top-title">${title}</span><div class="top-search">⌕ Search projects, OneDrive files or ask DOVA <span style="margin-left:auto">⌘ K</span></div><div class="top-actions"><span class="icon-btn">?</span><span class="icon-btn">VA</span></div></header><main class="content">${body(type)}</main></section></div>`;
}

document.querySelector('#desktop-grid').innerHTML = screens.map(([id,title,type])=>`<div class="artboard-wrap"><div class="artboard-label">${id} · ${title.toUpperCase()}</div>${shell(title,type)}</div>`).join('');
document.querySelector('#mobile-grid').innerHTML = screens.map(([id,title,type])=>`<div class="artboard-wrap"><div class="artboard-label">M-${id.slice(2)} · ${title.toUpperCase()}</div>${shell(title,type,true)}</div>`).join('');

const focusType = new URLSearchParams(window.location.search).get('focus');
const focusedScreen = screens.find(([, , type]) => type === focusType);
if (focusedScreen) {
  document.body.innerHTML = `<main style="padding:32px"><div class="artboard-wrap"><div class="artboard-label">${focusedScreen[0]} · ${focusedScreen[1].toUpperCase()}</div>${shell(focusedScreen[1], focusedScreen[2])}</div></main>`;
}
