/** Generated by @lead/vector [codex] · 2026-08-24 */
import type { Metadata } from "next";
import { getChatGPTUser } from "./chatgpt-auth";
import { HubDashboard } from "./components/hub-dashboard";

export const metadata: Metadata = {
  title: "DOVA Hub",
  description: "The secure operating view for DOVA Futures products and workspaces.",
  other: { "codex-preview": "development" },
};

export default async function Home() {
  const user = await getChatGPTUser();
  return <HubDashboard userName={user?.displayName ?? "Vollmann Akarakiri"} userEmail={user?.email ?? null} />;
}
