"use client";

/** Generated by @lead/vector [codex] · 2026-09-07 */
import { broadcastResponseToMainFrame } from "@azure/msal-browser/redirect-bridge";
import { useEffect, useRef, useState } from "react";

// Keep this route outside Hub authentication and MSAL providers: only the
// bridge may consume the popup response before it reaches the opening window.
export default function MicrosoftRedirect() {
  const started = useRef(false);
  const [failed, setFailed] = useState(false);

  useEffect(() => {
    if (started.current) return;
    started.current = true;
    void broadcastResponseToMainFrame().catch(() => setFailed(true));
  }, []);

  return failed
    ? <p role="alert">Microsoft sign-in could not return to the Hub. Close this window and try connecting again.</p>
    : <p role="status">Completing Microsoft sign-in…</p>;
}
