"""Build the public-safe snapshot used by the legacy Hub launcher."""

from __future__ import annotations

import argparse
import json
from datetime import datetime
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]

# This artifact may be published without authentication. Keep its data curated
# here; never derive it by scanning workspace memory, client jobs, or documents.
PUBLIC_PRODUCTS: tuple[dict[str, object], ...] = (
    {
        "slug": "dova-futures-intelligence",
        "purpose": "Private DOVA product Hub and intelligence dashboard.",
        "status": "Private Hub deployed",
        "codePath": "workspaces/dova-futures-intelligence/",
        "nextAction": "Open the private Hub for current operational details.",
        "registered": True,
        "projectPath": "workspaces/dova-futures-intelligence/PROJECT.md",
        "statusPath": "",
    },
    {
        "slug": "website",
        "purpose": "Public DOVA Futures company website.",
        "status": "Separated into its dedicated repository",
        "codePath": "Dblackone/Dova-futures-website",
        "nextAction": "Use the product repository for current website work.",
        "registered": True,
        "projectPath": "workspaces/website/PROJECT.md",
        "statusPath": "",
    },
    {
        "slug": "preorder-store",
        "purpose": "DOVA pre-order product application.",
        "status": "Separated into its dedicated repository",
        "codePath": "Dblackone/Dova-preorder",
        "nextAction": "Use the product repository for current pre-order work.",
        "registered": True,
        "projectPath": "workspaces/preorder-store/PROJECT.md",
        "statusPath": "",
    },
)


def build(root: Path) -> dict[str, object]:
    # Retain the root parameter for the CLI/test contract, but deliberately do
    # not read repository workspace content into this public artifact.
    del root
    return {
        "generatedAt": datetime.now().astimezone().strftime("%Y-%m-%d %H:%M %Z"),
        "workspaces": [dict(product) for product in PUBLIC_PRODUCTS],
    }


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--root", type=Path, default=ROOT, help="Repository root (not scanned; retained for compatibility)")
    parser.add_argument("--output", type=Path, default=Path(__file__).with_name("snapshot.js"), help="Snapshot JavaScript path")
    args = parser.parse_args()
    payload = json.dumps(build(args.root.resolve()), ensure_ascii=False, indent=2)
    args.output.write_text(f"// Generated by build_snapshot.py. Do not edit by hand.\nwindow.DOVA_HUB_SNAPSHOT = {payload};\n", encoding="utf-8")
    print(f"Wrote {args.output}")


if __name__ == "__main__":
    main()
