// Generated by build_snapshot.py. Do not edit by hand.
window.DOVA_HUB_SNAPSHOT = {
  "generatedAt": "2026-08-24 04:32 W. Central Africa Standard Time",
  "workspaces": [
    {
      "slug": "dova-futures-intelligence",
      "purpose": "Private DOVA product Hub and intelligence dashboard.",
      "status": "Private Hub deployed",
      "codePath": "workspaces/dova-futures-intelligence/",
      "nextAction": "Open the private Hub for current operational details.",
      "registered": true,
      "projectPath": "workspaces/dova-futures-intelligence/PROJECT.md",
      "statusPath": ""
    },
    {
      "slug": "website",
      "purpose": "Public DOVA Futures company website.",
      "status": "Separated into its dedicated repository",
      "codePath": "Dblackone/Dova-futures-website",
      "nextAction": "Use the product repository for current website work.",
      "registered": true,
      "projectPath": "workspaces/website/PROJECT.md",
      "statusPath": ""
    },
    {
      "slug": "preorder-store",
      "purpose": "DOVA pre-order product application.",
      "status": "Separated into its dedicated repository",
      "codePath": "Dblackone/Dova-preorder",
      "nextAction": "Use the product repository for current pre-order work.",
      "registered": true,
      "projectPath": "workspaces/preorder-store/PROJECT.md",
      "statusPath": ""
    }
  ]
};
