// Generated by build_snapshot.py. Do not edit by hand.
window.DOVA_HUB_SNAPSHOT = {
  "generatedAt": "2026-08-24 02:13 W. Central Africa Standard Time",
  "workspaces": [
    {
      "slug": "bim-standards",
      "purpose": "The firm-wide Revit naming system (projects, sheets,",
      "status": "Tools verified live in Revit (2 bugs fixed); Architecture .rte built; QA on real firm project pending",
      "codePath": "`bim-standards/`",
      "nextAction": "[ ] **Independent checker review of BIM-04 naming updates** — verify the",
      "registered": true,
      "projectPath": "workspaces/bim-standards/PROJECT.md",
      "statusPath": "workspaces/bim-standards/memory/status.md"
    },
    {
      "slug": "client-jobs",
      "purpose": "Container for every paid client project — documents,",
      "status": "3 active: FHS Pool (Ibafo), C.K. Musa road (Afuze), Hall of Worship (Osogbo)",
      "codePath": "`projects/`",
      "nextAction": "[ ] **ROAD: client decision on QTE-2026-001** — quote is approved by the",
      "registered": true,
      "projectPath": "workspaces/client-jobs/PROJECT.md",
      "statusPath": "workspaces/client-jobs/memory/status.md"
    },
    {
      "slug": "company-ops",
      "purpose": "Internal and administrative work not tied to one client",
      "status": "Product Hub reorganization complete on branch; independent checker pending",
      "codePath": "`automations/`, registers, admin docs",
      "nextAction": "[ ] **Complete the domain handoff** — transfer `dovafutures.com` from this",
      "registered": true,
      "projectPath": "workspaces/company-ops/PROJECT.md",
      "statusPath": "workspaces/company-ops/memory/status.md"
    },
    {
      "slug": "document-templates",
      "purpose": "The canonical library of branded company document",
      "status": "10 templates (incl. 00-Letterhead) + design system; Express wiring pending",
      "codePath": "`documents/` (+ `documents/_ds/`, `scripts/`)",
      "nextAction": "[ ] **GATE — principal reviews the Phase 2 samples.** `drafts/samples/` (ten",
      "registered": true,
      "projectPath": "workspaces/document-templates/PROJECT.md",
      "statusPath": "workspaces/document-templates/memory/status.md"
    },
    {
      "slug": "dova-futures-intelligence",
      "purpose": "Hybrid DOVA Intelligence and Hub experience: cloud-accessible oversight with an optional local-system execution/model layer.",
      "status": "Hub promoted; domain transfer pending; intelligence implementation deferred",
      "codePath": "`workspaces/dova-futures-intelligence/`; overview artifact in `hub/`",
      "nextAction": "Principal review and edit of the full desktop/mobile UX prototype.",
      "registered": true,
      "projectPath": "workspaces/dova-futures-intelligence/PROJECT.md",
      "statusPath": "workspaces/dova-futures-intelligence/memory/status.md"
    },
    {
      "slug": "preorder-store",
      "purpose": "Preorder and e-commerce platform for catalog, cart, Paystack checkout, order tracking, and administration.",
      "status": "Migrated; external tests pass, launch configuration remains",
      "codePath": "[external repository](https://github.com/Dblackone/Dova-preorder)",
      "nextAction": "Run an independent security/QA review of checkout, webhook verification, order transitions, and admin authentication in the external repository.",
      "registered": true,
      "projectPath": "workspaces/preorder-store/PROJECT.md",
      "statusPath": "workspaces/preorder-store/memory/status.md"
    },
    {
      "slug": "website",
      "purpose": "Public lead-generation and brand-credibility website for DOVA Futures Limited.",
      "status": "Source/default Pages verified; `dovafutures.com` transfer from Hub repo pending",
      "codePath": "[external repository](https://github.com/Dblackone/Dova-futures-website)",
      "nextAction": "Transfer `dovafutures.com` from the Hub repository's Pages settings to `Dova-futures-website`, then verify DNS, HTTPS, and the deployed content.",
      "registered": true,
      "projectPath": "workspaces/website/PROJECT.md",
      "statusPath": "workspaces/website/memory/status.md"
    }
  ]
};
