"""Read-only repository metadata for the DOVA Intelligence dashboard.

Generated by @qa/quartz [codex] · 2026-08-03
"""

from __future__ import annotations

import re
from dataclasses import dataclass
from pathlib import Path


@dataclass(frozen=True)
class ProjectRecord:
    slug: str
    status: str


@dataclass(frozen=True)
class RepositorySnapshot:
    projects: tuple[ProjectRecord, ...]
    intelligence_status: str
    next_action: str

    @classmethod
    def load(cls, repo_root: str | Path) -> "RepositorySnapshot":
        root = Path(repo_root).resolve()
        registry = root / "company" / "registry.md"
        projects: list[ProjectRecord] = []
        if registry.exists():
            for line in registry.read_text(encoding="utf-8").splitlines():
                match = re.match(r"\| \[`([^`]+)`\]\([^)]*\)\s*\|.*\|.*\|.*\|\s*(.*?)\s*\|$", line)
                if match:
                    projects.append(ProjectRecord(match.group(1), match.group(2)))

        workspace = root / "workspaces" / "dova-futures-intelligence" / "memory"
        status = _field(workspace / "status.md", "**Status:**") or "Status unavailable"
        next_action = _first_numbered_item(workspace / "next-up.md") or "No next action recorded"
        return cls(tuple(projects), status, next_action)

    def compact_text(self, max_projects: int = 4) -> str:
        lines = [f"PROJECTS  {len(self.projects)}", self.intelligence_status]
        for project in self.projects[:max_projects]:
            lines.append(f"• {project.slug}: {project.status}")
        if len(self.projects) > max_projects:
            lines.append(f"+ {len(self.projects) - max_projects} more")
        return "\n".join(lines)


def _field(path: Path, prefix: str) -> str | None:
    if not path.exists():
        return None
    for line in path.read_text(encoding="utf-8").splitlines():
        if line.startswith(prefix):
            return line[len(prefix):].strip().rstrip("  ")
    return None


def _first_numbered_item(path: Path) -> str | None:
    if not path.exists():
        return None
    for line in path.read_text(encoding="utf-8").splitlines():
        if re.match(r"\d+\.\s+", line):
            return re.sub(r"^\d+\.\s+", "", line).strip()
    return None
